info:
  name: Patch Task
  type: http
  seq: 1

http:
  method: PATCH
  url: https://super-duper-invention-9qjrqj94jp93pj9v-4000.app.github.dev/api/v1/tasks/f8f14927-2289-4905-a31d-1d7a2c39b3f1
  body:
    type: json
    data: |-
      {
        "title": "Learn CI CD"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
​